theme: jekyll-theme-cayman
title: Hanna's Drafts of El Camino de Santiago.
description: 산티아고 길에 대한 기록 초안 <가제:길이 나의 집인 나날>
#plugins:
#  - jekyll-relative-links
#relative_links:
#  enabled: true
#  collections: true
#include:
#  - CONTRIBUTING.md
#  - README.md
#  - LICENSE.md
#  - COPYING.md
#  - CODE_OF_CONDUCT.md
#  - CONTRIBUTING.md
#  - ISSUE_TEMPLATE.md
#  - PULL_REQUEST_TEMPLATE.md
#markdown: kramdown
